function J_PHI = calc_J_PHI(c3,c7,q2,q3,q4,q5,q6)
%CALC_J_PHI
%    J_PHI = CALC_J_PHI(C3,C7,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Mar-2020 13:05:20

J_PHI = [0.0,c3.*sin(q6).*(cos(q4)+1.0).*(cos(q3).*sin(q2)+cos(q2).*sin(q4)-cos(q3).*cos(q4).*sin(q2)).*(-8.0./1.25e+2)-c7.*cos(q2).*cos(q5).*(cos(q4).^2-1.0).*(8.0./1.25e+2),c3.*cos(q2).*sin(q3).*sin(q6).*(cos(q4)-1.0).*(cos(q4)+1.0).*(8.0./1.25e+2),c3.*sin(q2).*sin(q6).*(8.0./1.25e+2)-c3.*cos(q4).*sin(q2).*sin(q6).*(8.0./1.25e+2)-c3.*cos(q4).^2.*sin(q2).*sin(q6).*(1.6e+1./1.25e+2)+c7.*cos(q4).*cos(q5).*sin(q2).*sin(q4).*(1.6e+1./1.25e+2)+c3.*cos(q2).*cos(q3).*cos(q4).*sin(q4).*sin(q6).*(1.6e+1./1.25e+2),c7.*sin(q2).*sin(q4).^2.*sin(q5).*(-8.0./1.25e+2),c3.*cos(q6).*(cos(q4)+1.0).*(-cos(q2).*cos(q3)+sin(q2).*sin(q4)+cos(q2).*cos(q3).*cos(q4)).*(-8.0./1.25e+2),0.0];
