function [E,W,Pr] = Calc_E_W_Pr1(q1,q2,q3,q4,q5,q6)
%CALC_E_W_PR1
%    [E,W,PR] = CALC_E_W_PR1(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    05-Jun-2020 01:17:42

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = sin(q5);
t13 = sin(q6);
t14 = t2.*t10;
t15 = t8.*t10;
t16 = t3.*(2.0./5.0);
t17 = t2.*t3.*t4;
t18 = t3.*t4.*t8;
t20 = t2.*t9.*(2.0./5.0);
t21 = t8.*t9.*(2.0./5.0);
E = [t20;t21;t16+1.7e+1./5.0e+1];
if nargout > 1
    t25 = t4.*t9.*t11.*(2.0./5.0);
    t19 = t5.*t16;
    t22 = -t17;
    t23 = t5.*t20;
    t24 = t5.*t21;
    t26 = t14+t18;
    t27 = t15+t22;
    t28 = t11.*t26.*(2.0./5.0);
    t29 = -t28;
    t30 = t11.*t27.*(2.0./5.0);
    W = [t20+t23+t30;t21+t24+t29;t16+t19+t25+1.7e+1./5.0e+1];
end
if nargout > 2
    Pr = [t20+t23+t30-t13.*(t6.*(t5.*t27-t2.*t9.*t11)+t12.*(t4.*t8+t3.*t14)).*(1.23e+2./5.0e+2)+t7.*(t11.*t27+t2.*t5.*t9).*(1.23e+2./5.0e+2);t21+t24+t29+t13.*(t6.*(t5.*t26+t8.*t9.*t11)+t12.*(t2.*t4-t3.*t15)).*(1.23e+2./5.0e+2)-t7.*(t11.*t26-t5.*t8.*t9).*(1.23e+2./5.0e+2);t16+t19+t25+t13.*(t6.*(t3.*t11-t4.*t5.*t9)+t9.*t10.*t12).*(1.23e+2./5.0e+2)+t7.*(t3.*t5+t4.*t9.*t11).*(1.23e+2./5.0e+2)+1.7e+1./5.0e+1];
end
