function A04 = calc_A04(q1,q2,q3,q4)
%CALC_A04
%    OUT1 = CALC_A04(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Mar-2020 04:42:57

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = sin(q1);
t7 = sin(q2);
t8 = sin(q3);
t9 = sin(q4);
t10 = t2.*t8;
t11 = t6.*t8;
t12 = t2.*t3.*t4;
t13 = t3.*t4.*t6;
t14 = -t12;
t15 = t10+t13;
t16 = t11+t14;
A04 = reshape([-t5.*t16+t2.*t7.*t9,t5.*t15+t6.*t7.*t9,t3.*t9-t4.*t5.*t7,0.0,t9.*t16+t2.*t5.*t7,-t9.*t15+t5.*t6.*t7,t3.*t5+t4.*t7.*t9,0.0,t4.*t6+t3.*t10,-t2.*t4+t3.*t11,-t7.*t8,0.0,t2.*t7.*(2.0./5.0),t6.*t7.*(2.0./5.0),t3.*(2.0./5.0)+1.7e+1./5.0e+1,1.0],[4,4]);
