function T67 = calc_T67(q7)
%CALC_T67
%    OUT1 = CALC_T67(Q7)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Mar-2020 04:42:30

t2 = cos(q7);
t3 = sin(q7);
T67 = reshape([t2,0.0,t3,0.0,-t3,0.0,t2,0.0,0.0,-1.0,0.0,0.0,0.0,-1.23e+2./5.0e+2,0.0,1.0],[4,4]);
end